export const SECTION_TOURS = {
  chat: {
    label: 'Chat',
    description: 'Gestión de conversaciones con clientes',
    steps: [
      {
        target: '[data-tour="sidebar"]',
        title: '🗂️ Panel de navegación',
        content: 'La barra lateral es el menú principal del panel. Haz clic en cualquier ícono para ir a esa sección. Puedes colapsarla con el botón de hamburguesa para ganar espacio en pantalla.',
        placement: 'right',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-list"]',
        title: '💬 Lista de conversaciones',
        content: 'Aquí aparecen todos los chats de tus clientes. Cada ítem muestra: avatar del cliente con punto verde si está online, nombre de usuario, hora del último mensaje y una vista previa del contenido. El número rojo indica mensajes sin leer.',
        placement: 'right',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-search"]',
        title: '🔍 Buscar conversaciones',
        content: 'Escribe el nombre del cliente para filtrar la lista en tiempo real. Muy útil cuando tienes muchos chats activos.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-filters"]',
        title: '⚙️ Filtros avanzados',
        content: 'Haz clic aquí para desplegar los filtros adicionales:\n• Solo no leídos — muestra únicamente chats con mensajes pendientes\n• Filtro por proceso — si usas el bot, filtra por el último botón que presionó el cliente\n• Etiquetas de color — organiza visualmente tus chats por categoría\n\nCuando hay un filtro activo, aparece el chip naranja "Filtros activos".',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-list-scroll"]',
        title: '📋 Ítems de la lista',
        content: 'Cada chat muestra:\n• Punto de color — verde si el cliente está conectado ahora mismo\n• Etiqueta de proceso — el último paso del bot que completó el cliente\n• Pill "Asignado" — si el chat está asignado a un operador específico\n\nHaz clic derecho sobre un chat para ver el menú rápido: archivar, anclar, vaciar historial o eliminar.',
        placement: 'right',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-view"]',
        title: '📨 Vista de conversación',
        content: 'Al seleccionar un chat de la lista, aquí se carga la conversación completa.\n\n• Cabecera — nombre, estado online y menú de acciones (anclar, archivar, bloquear, eliminar)\n• Área de mensajes — el cliente aparece a la izquierda y el operador a la derecha; haz clic en un mensaje para responderlo con cita\n• Imágenes, PDFs y audios se visualizan directamente en el chat',
        placement: 'left',
        disableBeacon: true,
      },
      {
        target: '[data-tour="chat-view"]',
        title: '✏️ Barra de escritura',
        content: 'En la parte inferior del chat encontrás los botones para comunicarte:\n• 😊 Emojis — panel de emojis por categorías\n• 📎 Adjuntar — sube imágenes o PDFs (también podés arrastrar y soltar al chat)\n• 🎤 Micrófono — graba un mensaje de voz\n• ➤ Enviar — o presioná Enter\n\n💡 Tip: escribí / para ver los comandos automáticos disponibles y responder con un clic.',
        placement: 'left',
        disableBeacon: true,
      },
    ],
  },

  clientes: {
    label: 'Clientes',
    description: 'Administración de clientes registrados',
    steps: [
      {
        target: '[data-tour="clients-page"]',
        title: '👥 Gestión de clientes',
        content: 'Esta sección centraliza toda la administración de tus clientes: podés ver su información, gestionar saldos, cambiar contraseñas, forzar cierre de sesión y más.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="clients-header-actions"]',
        title: '⚡ Acciones principales',
        content: 'Los tres botones del encabezado:\n• Exportar CSV — descarga la lista completa de clientes con todos sus datos\n• Importar CSV — carga clientes en masa desde un archivo de planilla\n• Nuevo cliente ➕ — crea un cliente ingresando usuario, contraseña, nombre completo, email, ID externo y CUIT/CUIL',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="clients-stats"]',
        title: '📊 Estadísticas rápidas',
        content: 'Tres tarjetas con datos en tiempo real:\n• Total clientes — cantidad total registrados en el sistema\n• Activos — clientes con cuenta habilitada\n• Inactivos — clientes con acceso desactivado\n\nLos números se actualizan automáticamente.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="clients-filters"]',
        title: '🔎 Búsqueda y filtros',
        content: 'Dos controles para encontrar clientes:\n• Campo de búsqueda — filtra por nombre de usuario, ID externo o CUIT/CUIL en tiempo real mientras escribís\n• Dropdown de estado — mostrá todos, solo activos o solo inactivos\n\nEl contador de resultados se actualiza según los filtros activos.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="clients-table"]',
        title: '📋 Tabla de clientes',
        content: 'Columnas disponibles:\n• Cliente — avatar generado, nombre de usuario e ID externo\n• Registro — fecha de alta\n• ID Externo — identificador del sistema origen\n• CUIT/CUIL — número fiscal\n• Estado — chip Activo (verde) o Inactivo (rojo)\n• Online — punto verde si está conectado ahora\n• Acciones — botones de operación\n\nHaz clic en una fila para abrir el perfil completo.',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="clients-table"]',
        title: '🛠️ Acciones por cliente',
        content: 'Cada fila tiene 5 botones de acción:\n• 👁️ Ver/Editar — abre el perfil con datos como nombre, email, CUIT, estado y saldo\n• 🔒 Cambiar contraseña — asigna una nueva contraseña al cliente\n• 🚪 Cerrar sesión — desloguea al cliente (habilitado solo si está online)\n• 💰 Gestionar saldo — carga o retira saldo con montos rápidos ($500 a $10.000) o monto personalizado\n• 🗑️ Eliminar — borra el cliente permanentemente (con confirmación)',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  usuarios: {
    label: 'Usuarios',
    description: 'Gestión de operadores y administradores',
    steps: [
      {
        target: '[data-tour="users-page"]',
        title: '👤 Gestión de usuarios internos',
        content: 'Aquí administras las cuentas de operadores y administradores que tienen acceso al panel. Cada usuario puede tener permisos distintos según su rol.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="users-add-btn"]',
        title: '➕ Nuevo operador',
        content: 'Crea una cuenta para un nuevo miembro del equipo. Vas a definir:\n• Nombre completo, usuario de acceso y email\n• Rol (Administrador, Gerente, Soporte, Operador)\n• Restricción horaria — si solo puede acceder entre determinadas horas\n• Permisos por módulo — qué puede ver, crear, editar y eliminar en cada sección',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="users-filters"]',
        title: '🔎 Buscar y filtrar usuarios',
        content: 'Tres controles:\n• Búsqueda por nombre o usuario\n• Filtro por estado: Todos / Activos / Inactivos\n• Filtro por rol: Todos / Admin / Cajero\n\nÚtil para encontrar rápidamente a un operador cuando el equipo crece.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="users-table"]',
        title: '📋 Tabla de operadores',
        content: 'Columnas disponibles:\n• Usuario — avatar, nombre e email\n• Rol — badge con color según el rol asignado\n• Estado — Activo o Inactivo\n• Online — si está conectado al panel ahora\n• Permisos — chips que resumen a qué módulos tiene acceso\n• Restricciones — horarios o módulos bloqueados\n• Acciones — editar, ver sesiones, cerrar sesión, activar/desactivar',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="users-table"]',
        title: '🛡️ Sistema de permisos',
        content: 'Al crear o editar un operador podés controlar con precisión qué puede hacer:\n• Por módulo: Chat, Clientes, Usuarios, Comandos, Cuentas, etc.\n• Por acción: Ver / Crear / Editar / Eliminar\n• Acceso a páginas: bloquear secciones específicas del panel\n\nAsí cada operador solo ve lo que necesita para su trabajo.',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  comandos: {
    label: 'Comandos',
    description: 'Respuestas automáticas personalizadas',
    steps: [
      {
        target: '[data-tour="commands-page"]',
        title: '⚡ Comandos automáticos',
        content: 'Los comandos permiten que los operadores respondan mensajes frecuentes en un clic. Cuando un cliente escribe una palabra clave, el sistema sugiere o responde automáticamente con el mensaje configurado.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="commands-add-btn"]',
        title: '➕ Crear nuevo comando',
        content: 'Al hacer clic se abre el formulario de creación:\n• Nombre — título descriptivo (ej: "Bienvenida")\n• Comando — la palabra trigger que lo activa (ej: /bienvenida)\n• Tipo de coincidencia — "Contiene" activa si aparece en cualquier parte del mensaje, "Exacto" solo si coincide exactamente\n• Mensaje — respuesta con soporte para negrita, tachado y emojis 😊\n• Estado — activo o deshabilitado',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="commands-filters"]',
        title: '🔎 Búsqueda y filtros',
        content: 'Encuentra comandos rápidamente:\n• Campo de búsqueda — filtra por nombre del comando o contenido de la respuesta\n• Dropdown — muestra todos, solo activos o solo inactivos\n\nEl resultado se actualiza en tiempo real mientras escribís.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="commands-grid"]',
        title: '🃏 Tarjetas de comandos',
        content: 'Cada tarjeta muestra:\n• Barra de color — identificador visual (6 colores disponibles, se asigna automáticamente)\n• Nombre del comando\n• Punto de estado — verde si activo, gris si inactivo\n• Trigger — la palabra clave en un chip (ej: /bienvenida)\n• Vista previa de la respuesta\n• ✏️ Editar — modifica nombre, trigger, mensaje y estado\n• Botón de estado — activa o desactiva el comando sin abrir el formulario',
        placement: 'top',
        disableBeacon: true,
      },
      {
        target: '[data-tour="commands-grid"]',
        title: '💡 Cómo usar los comandos',
        content: 'En la vista de chat, cuando un operador escribe "/" en el campo de texto, aparece automáticamente el listado de comandos disponibles. Seleccionás uno y el mensaje se completa al instante. También puedes configurar que se envíen automáticamente sin intervención manual.',
        placement: 'top',
        disableBeacon: true,
      },
    ],
  },

  notificaciones: {
    label: 'Notificaciones',
    description: 'Campañas de push notifications',
    steps: [
      {
        target: '[data-tour="push-page"]',
        title: '🔔 Push Notifications',
        content: 'Envía notificaciones al navegador o celular de tus clientes incluso cuando no están en tu sitio. Ideal para recordarles que tienen bonos disponibles, premios ganados o eventos activos.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="push-content"]',
        title: '📑 Tipos de campaña',
        content: 'Las pestañas organizan diferentes estrategias de notificación:\n• Push directas — envío inmediato a todos o segmentos específicos\n• Retención — se envía X días después del registro para recuperar inactivos\n• Reconsumo — recordatorio cuando llevan N días sin operar\n• Engagement — mensajes programados en días y horarios específicos de la semana\n• VIP — campañas exclusivas para clientes de alto valor\n• Onboarding — secuencia de bienvenida para nuevos clientes\n• Suscriptores — gestiona quién tiene habilitadas las notificaciones\n• Ajustes — configuración general de FCM Firebase',
        placement: 'top',
        disableBeacon: true,
      },
      {
        target: '[data-tour="push-content"]',
        title: '✏️ Campos de una campaña',
        content: 'Para cada campaña configurás:\n• Título — encabezado de la notificación (visible en el dispositivo)\n• Mensaje — cuerpo del texto\n• Imagen — imagen de previsualización en la notificación\n• Días de espera — cuántos días después del evento se activa (Retención/Reconsumo)\n• Día y hora — para Engagement, qué días de la semana y a qué hora\n\nEl botón "Enviar ahora" hace un test de envío inmediato.',
        placement: 'top',
        disableBeacon: true,
      },
    ],
  },

  modales: {
    label: 'Modales',
    description: 'Diseñador de popups para el casino',
    steps: [
      {
        target: '[data-tour="modals-page"]',
        title: '🎨 Popups en Vivo',
        content: 'Diseña ventanas emergentes que aparecen automáticamente en el chat de tus clientes. Son perfectas para anunciar promociones, bonos de bienvenida, eventos especiales o comunicados importantes.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="modals-page"]',
        title: '📊 Estadísticas de popups',
        content: 'Las tarjetas del encabezado muestran:\n• Plantillas — cuántos diseños guardados tienes disponibles\n• Popups enviados — total de veces que se mostraron a clientes\n• Programados — popups con envío agendado para una fecha futura',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="modals-content"]',
        title: '✏️ Formulario de creación',
        content: 'Panel izquierdo — configuras el popup:\n• Título y Mensaje — el texto que verá el cliente\n• Imagen — sube una imagen de fondo o promocional\n• CTA (Call to Action) — texto y acción del botón: Abrir Chat, Cargar Fichas, Ver Promociones, Ruleta, URL personalizada, etc.\n• Audiencia — Todos los clientes, solo Activos, o solo VIP\n• Programar — activa para elegir fecha y hora de envío automático\n• Diseño — elige entre múltiples estilos visuales (Gold, Silver, etc.)',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="modals-content"]',
        title: '👁️ Vista previa + Plantillas',
        content: 'Panel derecho — la previsualización se actualiza en tiempo real mientras editás el formulario. Ves exactamente cómo verá el cliente el popup antes de enviarlo.\n\nTambién puedes guardar configuraciones como plantillas reutilizables y cargarlas rápidamente para campañas futuras similares.',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  bot: {
    label: 'Bot',
    description: 'Constructor visual de flujos de bot',
    steps: [
      {
        target: '[data-tour="bot-page"]',
        title: '🤖 Constructor de Bot',
        content: 'El bot atiende automáticamente a los clientes antes de derivarlos a un operador humano. Aquí diseñas el flujo conversacional de forma visual, sin necesidad de programar.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="bot-content"]',
        title: '🗂️ Panel de pantallas (izquierda)',
        content: 'Cada "pantalla" es un paso de la conversación. El flujo comienza siempre en la pantalla raíz (marcada con badge "Root"). Desde allí el cliente navega según sus respuestas.\n\n• Para agregar una pantalla: botón "+" en la parte inferior\n• Para reordenar: arrastrá las tarjetas\n• La pantalla activa se resalta y se carga en el editor central',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="bot-content"]',
        title: '✏️ Editor de pantalla (centro)',
        content: 'Cada pantalla puede tener tres tipos de elementos:\n• 💬 Mensaje — texto que el bot le enviará al cliente (soporta variables como {{banco.alias}})\n• 🔘 Botón — opción clickeable que lleva a otra pantalla o ejecuta una acción\n• 📝 Formulario — solicita datos al cliente (nombre, DNI, monto, etc.) con validación\n\nArrastrá los elementos para reordenarlos. El lápiz edita, la papelera elimina.',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="bot-content"]',
        title: '📱 Vista previa (derecha)',
        content: 'El panel derecho simula exactamente cómo verá el cliente el bot en el chat. Se actualiza en tiempo real mientras editas. Puedes hacer clic en los botones de la previsualización para navegar el flujo completo y verificar que funcione correctamente antes de activarlo.',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  events: {
    label: 'Eventos',
    description: 'Juegos y eventos interactivos',
    steps: [
      {
        target: '[data-tour="events-page"]',
        title: '🎮 Eventos y Juegos',
        content: 'Crea experiencias de juego interactivas para tus clientes: sorteos, quizzes, ruletas, tragamonedas, raspaditas y más. Los eventos gamifican la plataforma y aumentan el tiempo de permanencia.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="events-tabs"]',
        title: '🗂️ Secciones principales',
        content: 'Las cuatro pestañas del evento:\n• Juegos — configura los mini-juegos disponibles y crea nuevos eventos\n• Agenda — programa cuándo se activa y desactiva cada evento automáticamente\n• Estadísticas — analiza participación, tasas de conversión y premios entregados\n• Premios — gestiona el banco de recompensas: saldos, giros, bonos, productos físicos',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="events-content"]',
        title: '🎲 Tipos de juegos disponibles',
        content: 'Nueve tipos de juego para elegir:\n• 🎰 Sorteo — el sistema elige un ganador al azar entre los participantes\n• ❓ Quiz — pregunta con múltiples opciones, el cliente que responda correctamente gana\n• 🃏 Raspa y Gana — el cliente raspa virtualmente para descubrir si ganó\n• 🎡 Ruleta — rueda giratoria con sectores de premios o mensajes\n• 🎰 Tragamonedas — 3 rodillos con símbolos, el cliente intenta alinearlos\n• ♦️ Rojo/Negro — apuesta al color de la siguiente carta\n• 💼 Maletín — elige entre varios maletines para descubrir el premio\n• 🪙 Cofre — abre cofres misteriosos con premios sorpresa\n• 🏆 Ranking — tabla de liderazgo, ganan los clientes con más actividad',
        placement: 'top',
        disableBeacon: true,
      },
      {
        target: '[data-tour="events-content"]',
        title: '⚙️ Configuración de un evento',
        content: 'Al crear un evento definís:\n• Título y descripción visible para el cliente\n• Premio: tipo (saldo, giros, bono, producto) y monto/cantidad\n• Duración y fechas de inicio/fin\n• Límite de participaciones por cliente\n• Configuración específica del juego (preguntas del quiz, símbolos de tragamonedas, sectores de ruleta, etc.)\n\nEl botón "Activar" publica el evento en vivo para los clientes.',
        placement: 'top',
        disableBeacon: true,
      },
    ],
  },

  metricas: {
    label: 'Métricas',
    description: 'Analítica y reportes del negocio',
    steps: [
      {
        target: '[data-tour="metrics-page"]',
        title: '📈 Panel de Métricas',
        content: 'Visualiza el rendimiento completo de tu operación: transacciones, retiros, clientes activos, tiempos de respuesta y más. Todo filtrable por rango de fechas.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="metrics-filters"]',
        title: '📅 Filtros de período',
        content: 'Controla el rango de fechas analizado:\n• Botones rápidos — Hoy / 7 días / 30 días / 90 días / Este mes\n• Personalizado — elige fecha de inicio y fin manualmente con los campos de fecha\n\nTodos los gráficos y tablas se actualizan automáticamente al cambiar el período.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="metrics-export"]',
        title: '📥 Exportar reportes',
        content: 'Dos formatos de descarga:\n• Excel — hoja de cálculo con todos los datos detallados, lista para análisis o envío a contabilidad\n• PDF — informe visual con gráficos incluidos, ideal para presentaciones o reportes ejecutivos',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="metrics-kpis"]',
        title: '🔢 KPIs principales',
        content: 'Ocho indicadores clave en la parte superior:\n• Total operaciones — cantidad de transacciones en el período\n• Aprobadas / Rechazadas / Pendientes — desglose por estado\n• Monto aprobado — suma total de dinero procesado\n• Monto promedio — ticket promedio por operación\n• Monto mínimo — operación más pequeña del período\n• Usuarios únicos — clientes distintos que operaron',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="metrics-charts"]',
        title: '📊 Gráficos de rendimiento',
        content: 'Visualizaciones interactivas:\n• Actividad en el tiempo — línea de conteo/monto por día (toggleable)\n• Distribución por proveedor — qué banco o método se usa más\n• Torta de estados — proporción aprobado/rechazado/pendiente\n• Patrón horario — en qué horas del día hay más operaciones\n\nPasa el cursor sobre cualquier punto para ver el valor exacto.',
        placement: 'top',
        disableBeacon: true,
      },
      {
        target: '[data-tour="metrics-charts"]',
        title: '🏆 Tabla de clientes top',
        content: 'Más abajo encontrarás el ranking de los clientes con mayor actividad:\n• Puedes ordenar por Monto total o por Cantidad de operaciones\n• Muestra: posición, usuario, cantidad de operaciones, monto total, promedio y máximo\n\nTambién hay una sección de distribución de montos por rango ($0-500, $500-1000, etc.).',
        placement: 'top',
        disableBeacon: true,
      },
    ],
  },

  retiros: {
    label: 'Retiros',
    description: 'Gestión de solicitudes de retiro',
    steps: [
      {
        target: '[data-tour="withdrawals-page"]',
        title: '💸 Gestión de Retiros',
        content: 'Aquí procesás las solicitudes de retiro de tus clientes. El sistema incluye detección de fraude automática con puntuación de riesgo y un flujo de aprobación paso a paso.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="withdrawals-tabs"]',
        title: '📑 Pestañas por estado',
        content: 'Los retiros se organizan en tres estados:\n• Pendiente — solicitudes nuevas que esperan revisión (con contador)\n• Aprobado — retiros ya procesados y confirmados\n• Rechazado — solicitudes denegadas con motivo registrado\n\nLas pestañas muestran el conteo de cada estado en tiempo real.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="withdrawals-filters"]',
        title: '🔎 Filtros de búsqueda',
        content: 'Encuentra retiros específicos usando:\n• Búsqueda — por nombre de usuario o referencia bancaria\n• Filtro de fecha — desde/hasta, con botones rápidos (Hoy, Ayer, Semana, Mes)\n\nMuy útil para auditorías o para responder consultas de clientes sobre un retiro específico.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="withdrawals-content"]',
        title: '📋 Tabla de retiros',
        content: 'Columnas de cada solicitud:\n• ID — número único de la operación\n• Usuario — cliente que solicitó el retiro\n• Monto — importe solicitado\n• CBU/Alias — cuenta bancaria destino\n• Titular — nombre del titular de la cuenta\n• WhatsApp — contacto de verificación\n• CUIL — verificación fiscal\n• Estado — indicador visual del pipeline de procesamiento\n\nHaz clic en el botón de expandir (▶) para ver el detalle completo.',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="withdrawals-content"]',
        title: '🛡️ Anti-fraude y aprobación',
        content: 'Al expandir una fila, ves dos paneles:\n\n1. Datos del retiro — información completa del cliente y cuenta destino\n\n2. Panel anti-fraude — puntuación de riesgo /100 con barra visual y alertas específicas (cuenta nueva, monto inusual, etc.)\n\nLos botones de acción (solo en Pendientes):\n• ✅ Aprobar — confirma el pago\n• ❌ Rechazar — cancela con campo para escribir el motivo\n\nEl pipeline visual muestra el estado: Creado → Anti-Fraude → Revisión → Completo.',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  cuentas: {
    label: 'Cuentas',
    description: 'Cuentas bancarias y movimientos',
    steps: [
      {
        target: '[data-tour="banks-page"]',
        title: '🏦 Cuentas Bancarias',
        content: 'Administra las cuentas donde tus clientes realizan sus depósitos. El sistema soporta múltiples proveedores bancarios que puedes activar o desactivar según lo necesites.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="banks-tabs"]',
        title: '🏷️ Proveedores bancarios',
        content: 'Las pestañas organizan las cuentas por tipo de proveedor:\n• HGCash — integración directa con API de pagos\n• Mercado Pago — cuentas de MercadoPago con token\n• Cuentas Manuales — CBU/CVU sin integración automática\n\nCada pestaña muestra el conteo de cuentas de ese tipo. Haz clic para gestionar ese grupo.',
        placement: 'bottom',
        disableBeacon: true,
      },
      {
        target: '[data-tour="banks-content"]',
        title: '🔍 Buscar y filtrar cuentas',
        content: 'Filtra las cuentas del proveedor activo:\n• Búsqueda — por nombre del titular, alias o CBU\n• Estado — Todas / Activas / Inactivas\n\nEl botón "Nueva cuenta" (esquina superior derecha) abre el formulario para agregar una cuenta nueva según el tipo de proveedor seleccionado.',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="banks-content"]',
        title: '💳 Tabla de cuentas',
        content: 'Columnas por cuenta:\n• Titular — nombre del propietario de la cuenta\n• CUIT — número fiscal del titular\n• Alias y CBU/CVU — datos bancarios (parcialmente ocultos con botón copiar)\n• Token/API — credencial de integración (visible/oculto con toggle)\n• Estado — activa o inactiva\n\nBotones de acción:\n• 📊 Ver movimientos — historial completo de operaciones\n• ✏️ Editar — modifica datos y credenciales\n• ⚡ Activar/Desactivar — habilita o deshabilita la cuenta\n• 🗑️ Eliminar — borra la cuenta (con confirmación)',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="banks-content"]',
        title: '📊 Historial de movimientos',
        content: 'Al hacer clic en "Ver movimientos" se abre un panel lateral con todo el historial de esa cuenta:\n• Filtros: rango de fechas (Hoy, Ayer, Semana, Mes o personalizado) y estado (Pagados/Pendientes/Rechazados)\n• Búsqueda por usuario o referencia\n• Tabla con: ID, fecha, monto, estado, referencia y usuario asociado\n• Para HGCash: balance en tiempo real con botón de actualizar\n• Botón de importar movimientos desde archivo',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },

  ajustes: {
    label: 'Ajustes',
    description: 'Configuración general del sistema',
    steps: [
      {
        target: '[data-tour="settings-page"]',
        title: '⚙️ Ajustes del sistema',
        content: 'Configura todos los aspectos de tu plataforma. Los cambios se aplican en tiempo real al guardar.',
        placement: 'center',
        disableBeacon: true,
      },
      {
        target: '[data-tour="settings-nav"]',
        title: '📑 Secciones disponibles',
        content: 'El menú izquierdo da acceso a cada categoría:\n• Mi perfil — nombre, avatar y datos del operador actual\n• Sistema — nombre de la empresa, logo, favicon y esquema de colores\n• Montos mínimos — depósito y retiro mínimo permitidos\n• APIs — clave de API, modelo de IA activo y costos\n• Banco de chat — proveedor bancario activo por tipo\n• Mensajes auto — plantillas de mensajes automáticos\n• Avanzado — configuración técnica del sistema\n• Soporte — integración con sistema de tickets\n• Temas — personalización visual del chat del cliente',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="settings-content"]',
        title: '🏢 Sistema — Identidad de marca',
        content: 'En la sección "Sistema" configuras la identidad visual:\n• Nombre de la empresa — aparece en el chat y notificaciones\n• Logo — imagen que se muestra en la cabecera del chat\n• Favicon — ícono de pestaña del navegador\n• Esquema de colores — paleta de colores del panel admin',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="settings-content"]',
        title: '🎨 Temas del chat',
        content: 'En la sección "Temas" personalizas la apariencia del widget de chat que ven tus clientes:\n• Tema visual — oscuro, claro, oceánico, etc.\n• Colores primarios y de acento\n• Estilo de burbujas de mensaje\n• Fondo del chat\n\nLos cambios se reflejan instantáneamente en la vista previa.',
        placement: 'auto',
        disableBeacon: true,
      },
      {
        target: '[data-tour="settings-content"]',
        title: '💬 Mensajes automáticos',
        content: 'En "Mensajes auto" configuras los mensajes que se envían solos en situaciones específicas:\n• Mensaje de bienvenida — cuando un cliente inicia el chat por primera vez\n• Mensaje fuera de horario — cuando no hay operadores disponibles\n• Mensaje de espera — cuando todos los operadores están ocupados\n• Respuesta automática — mientras el bot procesa una solicitud\n\nPuedes usar variables como {{nombre}} para personalizar el mensaje.',
        placement: 'auto',
        disableBeacon: true,
      },
    ],
  },
}

export const ALL_SECTIONS = Object.entries(SECTION_TOURS).map(([id, cfg]) => ({
  id,
  label: cfg.label,
  description: cfg.description,
}))
